name: file_picker
description: A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
homepage: https://github.com/miguelpruivo/plugins_flutter_file_picker
repository: https://github.com/miguelpruivo/flutter_file_picker
issue_tracker: https://github.com/miguelpruivo/flutter_file_picker/issues
publish_to: none
version: 10.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_plugin_android_lifecycle:
    git: https://github.com/kumsumit/flutter_plugin_android_lifecycle.git
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  ffi: ^2.1.4
  path: ^1.9.1
  win32: ^5.14.0
  cross_file: ^0.3.4+2
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.mr.flutter.plugin.filepicker
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerIO
      ios:
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerIO
      web:
        pluginClass: FilePickerWeb
        fileName: _internal/file_picker_web.dart
      macos:
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerMacOS
      windows:
        dartPluginClass: FilePickerWindows
      linux:
        dartPluginClass: FilePickerLinux
